apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-g4vx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-nssd-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-g4vx@sha256:208139294d4fa8c1924bb83ad41e9e07124314c0db2d1b6bbd09965bac73f6da
        name: my-go
        resources: {}
status: {}
